name: edit_distance
description: Implementation of string distance algorithms for advanced text comparison.
version: 0.4.1
author: Kwang Yul Seo <email@example.com>
homepage: https://github.com/kseo/edit_distance

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
